import Navbar from "@/components/Header/Navbar";
import "./globals.css";
import Layout from "@/components/Layout";
import { ShoppingCartContextProvider } from "@/context/ShoppingCartContext";
import Banner from "@/components/Header/Banner";
import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
  title: "My Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
        <AuthProvider>
        <ShoppingCartContextProvider>
          <Banner />
          <Navbar />
          <Layout>{children}</Layout>
        </ShoppingCartContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
